services:
  web:
    container_name: web-container
    build: .
    ports:
      - "8080:8080"
#    volumes:
#      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    container_name: redis-container
    image: "redis:7.0.4"
    expose: 
      - 6379


